// <auto-generated />
using Marsen.NetCore.DA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Marsen.NetCore.DA.Migrations.Phobos
{
    [DbContext(typeof(PhobosContext))]
    partial class PhobosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Marsen.NetCore.DA.Models.Shop", b =>
                {
                    b.Property<long>("Shop_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Shop_IsEnable");

                    b.Property<string>("Shop_Title");

                    b.HasKey("Shop_Id");

                    b.ToTable("Shop");
                });
#pragma warning restore 612, 618
        }
    }
}
